### ISSUE TITLE
Saludos, no hay paquetes que descargar hoy

### ISSUE THREAD

**Issue by manonfire** [luisiturrios1/python-cfdiclient#18]
¡Buenos dias!

Gusto saludarte, a decir verdad desde que nos conocimos no he actualizado el código que has seguido actualizando, y hoy el SAT no me devuelve ningún paquete para descargar ¿crees que deba de actualizar? o ¿mas bien es tema del SAT?

¡gracias y saludos!

**Comment by luisiturrios** [comment]
Actualizar es lo mas recomendable, te sugiero que lo hagas en un ambiente
de stage para que no afectes tus sistemas productivos.

**Comment by luisiturrios1** [comment]
@manonfire  ¿Aun tienes problemas?
