### ISSUE TITLE
Metadatos de los CFDI

### ISSUE THREAD

**Issue by OdinChav** [luisiturrios1/python-cfdiclient#19]
Hola. Gracias por la herramienta. Está maravillosa.
Intenté de varias formas descargar los metadatos de las facturas de un cierto periodo sin éxito. ¿Crees que sea posible hacerlo con cfdiclient?

**Comment by luisiturrios1** [comment]
en tipo_solicitud tienes que incluir la palabra de esta manera `Metadata `

**Comment by OdinChav** [comment]
Uff... yo ya estaba haciendo parsing de los cfdi's descargados. Gracias!
