### ISSUE TITLE
Python 2.7

### ISSUE THREAD

**Issue by ivanporras** [luisiturrios1/python-cfdiclient#20]
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters

**Comment by luisiturrios1** [comment]
Puedes dar más detalles

**Comment by ivanporras** [comment]
estoy intentando correr la peticion con python 2.7, al momento de crear la solicitud me retorna ese error

**Comment by ivanporras** [comment]
El error no sucede cuando lo hago con python 3.8

**Comment by luisiturrios1** [comment]
Es necesario Python 2.7 ? Ya está deprecado

**Comment by ivanporras** [comment]
de hecho ya lo solucione hare un fork y te paso un pull request

**Comment by luisiturrios1** [comment]
Súper me avisas y subo la actualización del paquete

**Comment by ivanporras** [comment]
Listo ahi hice el pull request super facil resolverlo.

**Comment by luisiturrios1** [comment]
Ya quedo desplegado en la version 1.4.2 https://pypi.org/project/cfdiclient/

**Comment by luisiturrios1** [comment]
Esperemos no afecte a los que utilizan en python3

**Comment by ivanporras** [comment]
No deberia en realidad ese parametro yo lo utilizo tambien en la version 3.6
