### ISSUE TITLE
Expresión impresa no válida. Expresión: 601

### ISSUE THREAD

**Issue by mdark1001** [luisiturrios1/python-cfdiclient#23]
Hola @luisiturrios1  al intentar validar el estatus de un XML arroja el mensaje: 

`{'codigo_estatus': 'Expresión impresa no válida. Expresión: 601', 'es_cancelable': None, 'estado': None}`

usando el siguiente código: 
`
from cfdiclient import Validacion
validacion = Validacion()

validacion.obtener_estado('LOAM9002065L1', 'SDC180921GL8', '33552.45', '7974074A-E45E-4D9C-8A64-02B4BB64A052')

`

Tendrás alguna idea?

**Comment by ivanporras** [comment]
me esta pasando lo mismo, ya lo intente por postman y añadiendo los ultimos digitos del sello y no me ha dejado

**Comment by melfloc** [comment]
Tengo el mismo error, al parecer este error se da al no cumplir con los formatos permitidos en la petición de validación, sin embargo al intentar realizar la validación con varios cfdis no encuentro algún patrón que señale alguna causa aparente entre aquellos que arrojan el error y los que no, todas mis peticiones se realizan de la misma forma pero aun así siempre me aparece el error en los mismos cfdis

**Comment by ivanporras** [comment]
@melfloc @mdark1001 parece que el sat ya lo arreglo el dia de hoy, ya esta funcionando. ya hice las pruebas y me funciono

**Comment by mdark1001** [comment]
@ivanporras  al parecer  era problema del servicio del SAT, confirmo que ya esta solventado.
