### ISSUE TITLE
SOLICITUD: {'id_solicitud': '2ce5e153-f3ec-4007-b7a5-20d45d93c4b9', 'cod_estatus': '404', 'mensaje': 'Error no controlado.'}

### ISSUE THREAD

**Issue by jhugomh** [luisiturrios1/python-cfdiclient#25]
Buenos días Luis,
        A partir del 3 de marzo las solicitudes regresa éste mensaje de error:
SOLICITUD: {'id_solicitud': '2ce5e153-f3ec-4007-b7a5-20d45d93c4b9', 'cod_estatus': '404', 'mensaje': 'Error no controlado.'}
SOLICITUD: {'cod_estatus': '5004', 'estado_solicitud': '0', 'codigo_estado_solicitud': None, 'numero_cfdis': '0', 'mensaje': 'No se encontro la informacion', 'paquetes': []}

¿Sabrás si hubo algún cambio en el SAT por el cuál la solicitud regresa error? ¿Alguna actualización para 4.0?

Saludos y muchas gracias

Hugo Martínez

**Comment by luisiturrios1** [comment]
Hola es probable que cambiaran la URL lo hacen seguido el detalle es que no tengo orita oportunidad de revisarlo. Podrías buscar en la documentación del sat y levantar un pull request

**Comment by jhugomh** [comment]
Hola Luis,
      Estoy buscando si cambiaron las URL del SAT pero lo que tienen
publicado es lo mismo. Voy a seguir buscando y te comento.

Saludos,
Hugo Martínez

**Comment by luisiturrios1** [comment]
Que mala onda, esta info te la dieron personas del SAT ?

**Comment by JuanCarlosV** [comment]
Tengo el mismo problema; 
ejemplo de una solicitud aceptada:
    `Solicitud: {'id_solicitud': 'd1a35b08-1bab-4756-9bbf-3a7f289bf760', 'cod_estatus': '5000', 'mensaje': 'Solicitud Aceptada'}`
    
respuesta de solicitud de descarga que estamos recibiendo ahora:
    `Solicitud: {'id_solicitud': '282618ae-2d9a-4562-9d1b-287232c40bee', 'cod_estatus': '404', 'mensaje': 'Error no controlado.'}`

**Comment by jhugomh** [comment]
Sí, el web service sigue dado de baja por parte del SAT. Varios sistemas que hacen uso del web service están reportando eso. Incluso algunos PAC están mandando éste anuncio:
**"Queremos informarte que algunos servicios del SAT están teniendo un comportamiento NO normalizado, y que esto pudiera estar afectando algunos de tus procesos, los servicios son:
Servicio de consulta Estado del Comprobante. Tiempos de respuesta más largos de lo normal. 
El servicio de descarga masiva Webservices esta respondiendo a todas las solicitudes con error 404 " Error no controlado"**

**Comment by JuanCarlosV** [comment]
Gracias por el dato @jhugomh  , ahora veo que el servicio me devuelve lo siguiente:
`{'id_solicitud': None, 'cod_estatus': '301', 'mensaje': 'XML Mal Formado'}` 

que igual supongo es parte del mismo problema.

**Comment by jhugomh** [comment]
A parte de que el webservice de Descarga Masiva sigue deshabilitado. Estoy buscando documentación si cambiaron los web services o algo por lo que arroja el error:
 {'id_solicitud': None, 'cod_estatus': '301', 'mensaje': 'XML Mal Formado'} 
Pero no he encontrado nada. ¿Alguien sabe si los habrán modificado?
Pregunté por Twitter al SAT, cuándo habilitaban el web service y si habría cambios y hasta borraron mi mensaje.

**Comment by JuanCarlosV** [comment]
Creo que si las urls hubieran camibado estuvieramos recibiendo otro tipo de respuesta/exception como un connection timeout por ej por la falta de respuesta.

**Comment by luisiturrios1** [comment]
Tengo una implementación en descargadorcfdi.com podrías revisar si jala ahí? Su código fuente es libre y está en GitHub también.

**Comment by JuanCarlosV** [comment]
> 

ModuleNotFoundError: No module named 'vine.five' cuando intento levantar los contenedores. falta la dependencia. la agregué al requirements.txt sin versión y mismo resultado. creo que te faltó agregar esa dependencia al requirements, si la tienes agregada que version usas?

**Comment by jhugomh** [comment]
Hice la prueba y marca error... (1048, "Column 'id_solicitud' cannot be null")

**Comment by JuanCarlosV** [comment]
Es por esto: {'id_solicitud': None, 'cod_estatus': '301', 'mensaje': 'XML Mal Formado'}

**Comment by luisiturrios1** [comment]
Si puedes ponérselo y eso va a generar el build cuando merge el pull

**Comment by JuanCarlosV** [comment]
> Si puedes ponérselo y eso va a generar el build cuando merge el pull

lo siento no entendí.

**Comment by jhugomh** [comment]
Ya me respondieron del SAT el día 4 de marzo dieron de baja el web service
de descarga masiva y según eso el 7 de marzo publicaron las nuevas
especificaciones.
Del nabo su dichosa comunicación.

**Comment by jhugomh** [comment]
Las URLs de los servicios ya están disponibles menos el de descarga.
https://cfdidescargamasivasolicitud.clouda.sat.gob.mx/Autenticacion/Autenticacion.svc         OK
https://cfdidescargamasivasolicitud.clouda.sat.gob.mx/SolicitaDescargaService.svc                 OK
https://cfdidescargamasivasolicitud.clouda.sat.gob.mx/VerificaSolicitudDescargaService.svc   OK
https://cfdidescargamasiva.clouda.sat.gob.mx/DescargaMasivaService.svc)/DescargaMasivaService.svc NO FUNCIONA

**Comment by JuanCarlosV** [comment]
Gracias por la info @jhugomh  pregunta: como te comunicaste con el SAT? 

En cuanto a las urls, veo que siguen siendo las mismas, sin embargo me sigue saltando el mismo error de xml mal formado. Aun no veo el pdf de la documentación que compartiste, supongo que hicieron cambios a la estructura requerida para realizar el soaprequest.? has revisado al go al respecto??

**Comment by jhugomh** [comment]
Hola Juan Carlos, les pregunté por Twitter y por algunos compañeros de otras empresas que están sufriendo igual que nosotros.
Aún no empiezo a revisar los cambios que hicieron, también ando full con otros proyectos, espero éste fin de semana leer el documento y ver que cambios se necesitan. Sólo espero que no salgan con más cambios como suele suceder.

**Comment by Mencrypto** [comment]
Yo estoy reviviendo un proyecto Java que tenía 2 años abandonado y justo me encuentro que andan cambiando los Web Services, pero ya detecté que el problema es el tipo de nodo **RfcReceptores**, debe agregarse ahora dentro de la solicitud de esta forma:
```
		<des:SolicitaDescarga>
			<des:solicitud xmlns:des="http://DescargaMasivaTerceros.sat.gob.mx" RfcEmisor="#Emisor" RfcReceptor="#Receptor" RfcSolicitante="#RFC" FechaFinal="#FF" FechaInicial="#FI" TipoSolicitud="#TipoSolicitud">
				<des:RfcReceptores><des:RfcReceptor>#Receptor</des:RfcReceptor></des:RfcReceptores>
				<Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
				</Signature>
			</des:solicitud>
		</des:SolicitaDescarga>
```

**Comment by JuanCarlosV** [comment]
Probé agregandole el nodo ActivityId y sigo teniendo el mismo problema. Probaré con esto que mencionas @Mencrypto 

Lo agregas solo en la solicitud de descarga?

**Comment by Mencrypto** [comment]
> Probé agregandole el nodo ActivityId y sigo teniendo el mismo problema. Probaré con esto que mencionas @Mencrypto
> 
> Lo agregas solo en la solicitud de descarga?

Si, en la versión anterior existía un nodo llamado RfcReceptor ahora ese nodo debe estar dentro del subelelemento RfcReceptores que a su vez es subelemento de solicitud, ya con eso no recibes el error 301 XML Mal Formado

**Comment by edwinve** [comment]
Aquí les dejo un vídeo con los nuevos cambios, con una mejor explicación.

https://www.youtube.com/watch?v=8SFB5ljxxgE

Espero esto pueda aportar a dejar mas claro como hacer la actualización

**Comment by JuanCarlosV** [comment]
Tengo el siguiente soap request y aún me sigue marcando xml mal formado

`<s:Envelope
	xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"
	xmlns:des="http://DescargaMasivaTerceros.sat.gob.mx"
	xmlns:xd="http://www.w3.org/2000/09/xmldsig#">
	<s:Header>
		<ActivityId CorrelationId="806aad0d-ef46-443b-9741-040c8e8e8c7d"
			xmlns="http://schemas.microsoft.com/2004/09/ServiceModel/Diagnostics">e906cfb4-f706-43de-94d0-5cc935be1aaa
		</ActivityId>
	</s:Header>
	<s:Body>
		<des:SolicitaDescarga>
			<des:solicitud RfcSolicitante="#Rfcsolicitante" FechaFinal="2022-03-14T15:06:22" FechaInicial="2022-03-13T15:06:22" TipoSolicitud="CFDI" RfcACuentaTerceros="" RfcReceptor="#Rfcreceptor">
				<RfcReceptores>
					<RfcReceptor/>
				</RfcReceptores>
				<Signature
					xmlns="http://www.w3.org/2000/09/xmldsig#">
					<SignedInfo>
						<CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
						<SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
						<Reference URI="#_0">
							<Transforms>
								<Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
							</Transforms>
							<DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
							<DigestValue>0q6DBjXhKIpmUVEmkAkxQsxtmMc=</DigestValue>
						</Reference>
					</SignedInfo>
					<SignatureValue>xyYYEy2ylk/yalwA/mxEi1FRWU9jhfoo1OARfZG37lulgTFrObYlqY3v4Yg+zVExs0VfnByJWygeuilqDWo6QbfuvpJx0uI4Wq7qUJno0m9smdCH8ph+drVS3b8Iw6DjBXQGPjW2GaUSxoUyITRJio1EJIt2Rsi2jOPhyI1RukAqUMxNblQ2ZItPW7Z6/2txpzRYWUZhvwTCc4WTMDr9b10f1Y7jEzhyphFvC5Ys6uNSGO0N5FIcLy+NgV5G++z6Vml5aN6bxeCqysV4Rbke9iDcmYMyt6Ijpm5mr0J0wf8rjzl8qb9jWBg3KRyZf9yi5UtgeS7C2PbQVPrW2UJJww==</SignatureValue>
					<KeyInfo>
						<X509Data>
							<X509IssuerSerial>
								<X509IssuerName>CN=AUTORIDAD CERTIFICADORA,O=SERVICIO DE ADMINISTRACION TRIBUTARIA,OU=SAT-IES Authority,emailAddress=contacto.tecnico@sat.gob.mx,street=AV. HIDALGO 77, COL. GUERRERO,postalCode=06300,C=MX,ST=CIUDAD DE MEXICO,L=CUAUHTEMOC,x500UniqueIdentifier=SAT970701NN3,unstructuredName=responsable: ADMINISTRACION CENTRAL DE SERVICIOS TRIBUTARIOS AL CONTRIBUYENTE</X509IssuerName>
								<X509SerialNumber>275106190557734483187066766829379318498983097136</X509SerialNumber>
							</X509IssuerSerial>
							<X509Certificate>MIIGljCCBH6gAwIBAgIUMDAwMDEwMDAwMDA1MDEwMzAzMzAwDQYJKoZIhvcNAQELBQAwggGEMSAwHgYDVQQDDBdBVVRPUklEQUQgQ0VSVElGSUNBRE9SQTEuMCwGA1UECgwlU0VSVklDSU8gREUgQURNSU5JU1RSQUNJT04gVFJJQlVUQVJJQTEaMBgGA1UECwwRU0FULUlFUyBBdXRob3JpdHkxKjAoBgkqhkiG9w0BCQEWG2NvbnRhY3RvLnRlY25pY29Ac2F0LmdvYi5teDEmMCQGA1UECQwdQVYuIEhJREFMR08gNzcsIENPTC4gR1VFUlJFUk8xDjAMBgNVBBEMBTA2MzAwMQswCQYDVQQGEwJNWDEZMBcGA1UECAwQQ0lVREFEIERFIE1FWElDTzETMBEGA1UEBwwKQ1VBVUhURU1PQzEVMBMGA1UELRMMU0FUOTcwNzAxTk4zMVwwWgYJKoZIhvcNAQkCE01yZXNwb25zYWJsZTogQURNSU5JU1RSQUNJT04gQ0VOVFJBTCBERSBTRVJWSUNJT1MgVFJJQlVUQVJJT1MgQUwgQ09OVFJJQlVZRU5URTAeFw0xOTA4MTYxNTA0MzJaFw0yMzA4MTYxNTA1MTJaMIIBMTE7MDkGA1UEAxMyUkVQUkVTRU5UQUNJT05FUyBJTkRVU1RSSUFMRVMgTU9DSElTIFMgQSBQIEkgREUgQ1YxOzA5BgNVBCkTMlJFUFJFU0VOVEFDSU9ORVMgSU5EVVNUUklBTEVTIE1PQ0hJUyBTIEEgUCBJIERFIENWMTswOQYDVQQKEzJSRVBSRVNFTlRBQ0lPTkVTIElORFVTVFJJQUxFUyBNT0NISVMgUyBBIFAgSSBERSBDVjELMAkGA1UEBhMCTVgxJDAiBgkqhkiG9w0BCQEWFWZpbmFuemFzQHJpbXNhbWV4LmNvbTElMCMGA1UELRMcUklNOTcwOTIyRUo1IC8gUk9aRzU5MDQzMEM4MjEeMBwGA1UEBRMVIC8gUk9aRzU5MDQzMEhTTERNQjAzMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyaWf5g7kTUYKs4wK7xR2RNzmKw665Uv08RrLlELnLp6kNuP3JVPMDlGSc05ekoYr536jZIl6QXUW3x/nvCr4dg5kqLOEMSVcUl1uisNFzfdF4pB/qCEr3yxzTTv4ExsodkLoD7g9Vc0jFuEF4EDcVWlp2QsVilesTsKp+hzFyrkFpjA1wEhXyiDTrshRDQpGK76pGRbK+x3slPuX9PSvnIQXZtYFptI9ZrkSymd+8icD2M8ZhGCYhGbF8pd1nSQIeKN5YB8AiAg72c/AZN4Puf9r6Deebgb04Z4axSrKRN0LpL04Hq1skMohQzsstHnfCwALyNJJrpa428tVVk+SQQIDAQABo08wTTAMBgNVHRMBAf8EAjAAMAsGA1UdDwQEAwID2DARBglghkgBhvhCAQEEBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwQGCCsGAQUFBwMCMA0GCSqGSIb3DQEBCwUAA4ICAQCclcbdVYwI0WCqV+VTI8nqqBPyAuLHjIj23Vf7kCRjY5nQUflZWNEmsysJ0uEJhwJXYAZ/TpCvqyQcW4YZQDhLTlBfzviMsYI+U6irRXidKqNfaIVs/OCR4OUDq1pjJCMT/IezrSgpql3qHkRMHRlwS7iuxvdnu8sxwEk2/sSm/kAUJvqSbk+JushyBZkN2wPJK35kNBUbKSXOPyPAuT91d+KCSVrG3FE9UH0V7jO3v+fg9MOZrUw0PaYjcd8QxlpEgwTxZyv15eh4F9I1t1JSd0MDFb8E2JLg+rU/zmgTLke+rXiMXIZihVxQT6mbhZXxSN1QdHLGPkbr8rhfTblMkEfTUvzSRe5YSVgIDPi7Fum/EF2exMAmdqGSf22yejB1FQ5sf+XZ/sKjHe9VvcLdvHwNklxq4todd/1hGmacC9Obnw+AjbFqjWZ2+4naZU4lLQR5cPwuBAxklUa9CjacgwMMCjakmtGH/ADsyACh/Bs8TreCtqmwqROpmBbT7vULZWg4ZO3OjjN0KuXlQUFrsGPAH/PGNY5R7Bh8d4zDSAlDw3dsmU4UPOFxtakWSp4fbh0bHZ2/PDh0OpbFONl7eJwzikdqbAghn8Um4P9tU6Q1XVNQKtf2m1pnDyuAaeJ4v9sjjjjW+lDkxHfOSEW+YwWf53I8f9+m8QZHwuGDaA==</X509Certificate>
						</X509Data>
					</KeyInfo>
				</Signature>
			</des:solicitud>
		</des:SolicitaDescarga>
	</s:Body>
</s:Envelope>`

**Comment by draxter90** [comment]
unicamente se debe de eliminar el prefijo des en el nodo SolicitaDescarga y en el nodo solicitud, ya con eso recibe la petición correctamente el SAT.

**Comment by luisiturrios1** [comment]
Gracias a todos por los inputs para realizar los cambios no hace mucho tenia un refactoring de este modulo y aproveche la ocasión para meterlo junto con los cambios del SAT.  #26 

Se genero la [versión 1.5.2](https://pypi.org/project/cfdiclient/) que contempla los nuevos cambios del SAT sin cambiar el contrato para que sus componentes sigan funcionando de manera adecuada pero agregando los nuevos campos de manera opcional

TODO: El campo RFC receptor podría recibir hasta 5 RFC de momento solo estaremos recibiendo uno para no cambiar el contrato pero veremos la forma de poder recibir hasta los 5.  

Les agradecería mucho me confirmen si les funciona o no

**Comment by JuanCarlosV** [comment]
@luisiturrios1 faltaría agregar este archivo en los commits?

`OSError: Error reading file './venv/lib/python3.8/site-packages/cfdiclient/autenticacion.xml': failed to load external entity "./venv/lib/python3.8/site-packages/cfdiclient/autenticacion.xml"`

revisé en el directorio donde se instala el package y parecen faltar los archivos xmls que agregaste; los agregué manualmente y ya funciona. gracias por el release!

**Comment by luisiturrios1** [comment]
Alguien sabe cómo indicarle al setup.py Que los agregué ?

**Comment by jhugomh** [comment]
Aún sigue sin funcionar el WS DescargaMasivaService.svc verdad?

https://cfdidescargamasiva.clouda.sat.gob.mx/DescargaMasivaService.svc

Saludos

**Comment by JuanCarlosV** [comment]
realice la actualización de esta libreria y ejecute una solicitud de descarga pero sigue en status aceptada, te informo del status cuando llegue a ese punto @jhugomh . creo recordar que las urls de los servicios (algunas o al menos hace tiempo) solo aceptaban POST request por lo que tu GET request desde el browser no funcione puede ser un falso positivo. me expliqué?

**Comment by jhugomh** [comment]
Hola Juan Carlos, hasta ahí llego yo también, hasta la solicitud aceptada:

SOLICITUD: {'cod_estatus': '5000', 'estado_solicitud': '1', 'codigo_estado_solicitud': '5000', 'numero_cfdis': '0', 'mensaje': 'Solicitud Aceptada', 'paquetes': []}

Ya de ahí no pasa y verificando la URL del servicio sigue sin estar activa.

**Comment by JuanCarlosV** [comment]
@jhugomh en teoría todo esta bien hasta el momento; el sat solo se esta tomando su tiempo para procesar la solicitud. 

@luisiturrios1 excelente gracias.

**Comment by luisiturrios1** [comment]
Listo seria la versión 1.5.5 la buena..  Que pena metí un buen de versiones sin funcionar =(

**Comment by draxter90** [comment]
El tema es que el sat lleva aceptando las solicitudes desde hace 4 dias pero no deja lista ninguna para descarga, esta tomando mas de 72 horas, esperemos lo puedan arreglar

**Comment by edwinve** [comment]
de casualidad alguien a pasado de un estado 1 en la solicitud?
a un estado dos al menos que es en proceso?
o un estado tres de terminado?

**Comment by JuanCarlosV** [comment]
no, yo tengo en estado 1 la solicitud desde hace 7 horas.

**Comment by edwinve** [comment]
> no, yo tengo en estado 1 la solicitud desde hace 7 horas, mi rango de fechas es de 1 día

mis rangos de pruebas también son de un día, parece entonces que los servidores del SAT no están funcionando de forma correcta

**Comment by JuanCarlosV** [comment]
así es parece no funcionar correctamente aún; cabe mencionar que el tiempo de procesamiento puede ser hasta 48 hrs o 72hrs, no recuerdo el dato exacto. checa el comentario de @draxter90

**Comment by JuanCarlosV** [comment]
sigo teniendo time outs, ustedes que tal su experiencia?

**Comment by Mencrypto** [comment]
> sigo teniendo time outs, ustedes que tal su experiencia?

Ya llevo unas 54 horas y aún estoy en Solicitud Aceptada.

**Comment by JuanCarlosV** [comment]
de mi parte sigo igual. nunca pasa de solicitud aceptada.

**Comment by JuanCarlosV** [comment]
hasta ayer por la tarde ya tuve una descarga correcta.

**Comment by jhugomh** [comment]
En éstos momento estoy tratando de hacer una descarga y después de una hora, sigue regresando el mismo estatus:

**cod_estatus': '5000', 'estado_solicitud': '1', 'codigo_estado_solicitud': '5000', 'numero_cfdis': '0',**

**Comment by JuanCarlosV** [comment]
esta tardando demasiado eso sí; los mios tardaron horas entre 3 y hrs

**Comment by Mencrypto** [comment]
> hasta ayer por la tarde ya tuve una descarga correcta.

Que suerte yo ya voy para 72 horas en el mismo estatus 
CodEstatus="5000" EstadoSolicitud="1" CodigoEstadoSolicitud="5000" NumeroCFDIs="0" Mensaje="Solicitud Aceptada"

**Comment by edwinve** [comment]
las mías ahora quedaron con un

{'cod_estatus': '5000', 'estado_solicitud': '5', 'codigo_estado_solicitud': '5006', 'numero_cfdis': '0', 'mensaje': 'Solicitud Aceptada', 'paquetes': []}

5006 = Error interno en el proceso

**Comment by luisiturrios1** [comment]
Cómo que cancelaron las viejas, volví a mandar una y jalo bien 

¿Pudieran confirmar para cerrar el isssue?

**Comment by edwinve** [comment]
> Cómo que cancelaron las viejas, volví a mandar una y jalo bien
> 
> ¿Pudieran confirmar para cerrar el isssue?

yo igual volví a mandar una pero nuevamente esta en estatus 1

**Comment by jhugomh** [comment]
> Cómo que cancelaron las viejas, volví a mandar una y jalo bien
> 
> ¿Pudieran confirmar para cerrar el isssue?

Igualmente mandé una solicitud y sigue en el mismos estatus...

**SOLICITUD: {'cod_estatus': '5000', 'estado_solicitud': '1', 'codigo_estado_solicitud': '5000', 'numero_cfdis': '0', 'mensaje': 'Solicitud Aceptada', 'paquetes': []}**

**Comment by vladixmir** [comment]
Hola, hasta el momento no he podido descargar, igual que @jhugomh recibo lo mismo:

Saludos a todos,

**Comment by JuanCarlosV** [comment]
> Cómo que cancelaron las viejas, volví a mandar una y jalo bien
> 
> ¿Pudieran confirmar para cerrar el isssue?

las solicitudes ya se realizan correctamente; lo que esta pasando es que sat nunca termina de procesar tu solicitud - estado_solicitud = 3

**Comment by draxter90** [comment]
Hola, alguien ya ha podido descargar correctamente solicitudes? A mi todas me las deja en 1

**Comment by edwinve** [comment]
> 

La verdad no las mías siguen igual en estatus 1, tal ves deberíamos preguntarle a @JuanCarlosV como realizo su actualización tal vez se nos este pasando algo y no estamos enviando la solicitud como corresponde.

**Comment by jhugomh** [comment]
Yo sigo con la misma situación, mandé usa solicitud y ya tiene 3 horas corriendo y el estatus sigue siendo el mismo: 
SOLICITUD: {'cod_estatus': '5000', 'estado_solicitud': '1', 'codigo_estado_solicitud': '5000', 'numero_cfdis': '0', 'mensaje': 'Solicitud Aceptada', 'paquetes': []}

El software Onefacture sigue igualmente sin funcionar la opcion de SAT Web Service... Indica el siguiente mensaje:

**Actualización de estatus: El servicio Web Service del SAT aún continua presentando intermitencias al actualizar el estatus, por lo tanto, continua sin enviarnos el paquete de XMLs solicitados o generando algunos errores no controlados por Onefacture. Por el momento solo queda esperar que el SAT comience a funcionar correctamente para que nuestro módulo de descarga también lo haga. Si el número de XMLs a descargar es menor a 15,000 puedes hacer tu descarga desde el módulo Descarga CFDI.**

**Comment by jhugomh** [comment]
Una pregunta, ¿Alguien de ustedes ha desarrollado el programa para la descarga de CFDI por el otro método que tiene el SAT para menos de 15,000 documentos? Aunque según recuerdo el problema era porque el otro método solicitaba un Captcha y ese era el problema para la automatización.

Saludos

**Comment by draxter90** [comment]
Parece que ya se puede consumir el wsdl a traves del metodo get

**Comment by jhugomh** [comment]
Yo aún sigo con el mismo estatus 5000, el día de hoy ya lleva 5 horas con una petición de prueba sin éxito... ¿Alguien a logrado descargar algo?

**Comment by edwinve** [comment]
Les comparto que por fin hasta el dia de hoy mis solicitudes se procesaron correctamente

{'cod_estatus': '5000', 'estado_solicitud': '3', 'codigo_estado_solicitud': '5000', 'numero_cfdis': '349', 'mensaje': 'Solicitud Aceptada', 'paquetes': ['D27238A61856_01']} **_(id del paquete cortado por privacidad)_**

estas solicitudes para mi fueron de prueba solicitando un día, esperemos que ya se encuentre funcionando correctamente

**Comment by jhugomh** [comment]
Buenos días, el día de hoy por fin pude realizar la descarga de los documentos, alrededor de 2,000 xml y tardó el proceso un poco más de un minuto, esperemos que el SAT ya tenga estabilizado el servicio.

Muchas gracias @luisiturrios1 

Saludos

**Comment by edwinve** [comment]
> Buenos días, el día de hoy por fin pude realizar la descarga de los documentos, alrededor de 2,000 xml y tardó el proceso un poco más de un minuto, esperemos que el SAT ya tenga estabilizado el servicio.
> 
> Muchas gracias @luisiturrios1
> 
> Saludos

Yo el jueves envié otras solicitudes y ayer domingo por la tarde ya estaban en estado 3 listas para descargar y todo se descargo de forma correcta.

Me parece que ya se esta normalizando el servicio.
