### ISSUE TITLE
el webservice de verificacion nunca devuelve la lista de paquetes

### ISSUE THREAD

**Issue by rccardero** [luisiturrios1/python-cfdiclient#27]
Hola Luis, 
Muchísimas gracias por su librería. Yo la llevaba usando varios meses, hasta que empezó a fallar por los cambios del SAT. Y ya actualicé a la nueva versión que publicaste y funciona la autenticación, la solicitud de descarga, pero no pasa de la verificación, ya que el webservice de verificación siempre responde que la solicitud es correcta, pero nunca devuelve la lista de paquetes para descargar con el webservice de descarga. Y luego de un tiempo da un error interno del webservice de verificación, pero no describe el error. Ya han pasado más de una semana que lo intento todos los días con tres FIEL pero sigue en el mismo estado. 
¿Ustedes pueden descargar bien del SAT después de los cambios que hizo el SAT?
Gracias de antemano, 
Roberto

**Comment by luisiturrios1** [comment]
La libreria esta operativa se dio seguimiento por acá #25
