### ISSUE TITLE
Recibo error 301 desde hace tres semanas

### ISSUE THREAD

**Issue by hectorHerreraTeigeiro** [luisiturrios1/python-cfdiclient#28]
Buenas tardes.   Desde hace tres semanas (inicio Marzo) estoy recibiendo error en todas las solicitudes:
{'cod_estatus': '301', 'id_solicitud': None, 'mensaje': 'XML Mal Formado'}
Hay ago reportado o tienen sugerencia para revisar?   Gracias !

**Comment by luisiturrios1** [comment]
#25
