### ISSUE TITLE
Codigo estado solicitud '5004'

### ISSUE THREAD

**Issue by AllanCastro24** [luisiturrios1/python-cfdiclient#40]
Hola, tengo ese error de solicitud en los cfdi y metadatos recibidos, con los emitidos no tengo mayor problema

![image](https://user-images.githubusercontent.com/66056538/170537802-9f00d041-5298-4e1b-b756-10d2a4a4dc6c.png)

**Comment by luisiturrios1** [comment]
[Consulta y recuperación de comprobantes (Nuevo)
](https://www.sat.gob.mx/consultas/42968/consulta-y-recuperacion-de-comprobantes-(nuevo))
 Evento | Mensaje  |  Observaciones
-- | -- | --
5004 | No se encontró la información | Indica que la solicitud de descarga que se está verificando no generó paquetes por falta de información.

**Comment by luisiturrios1** [comment]
@AllanCastro24 si te gusta el proyecto déjanos una estrella ⭐️
