### ISSUE TITLE
Problema con CFDI Recibidos

### ISSUE THREAD

**Issue by AllanCastro24** [luisiturrios1/python-cfdiclient#44]
Alguien tiene problemas para descargar los CFDI Recibidos?

**Comment by manonfire** [comment]
Hola, dejé de usar la libreria unos meses y estoy de regreso, y me está pasando lo mismo, al parecer el código de Error es 301 "XML mal formado" 

@luisiturrios1 ya actualicé la libreria y revisé nuevamente el código, no encuentro la razón por la cual no descarga los CFDI Recibidos ¿a ti te funciona bien?

¡¡Saludos!!

**Comment by manonfire** [comment]
Hola @AllanCastro24 volví a usar la libreria desde 0 y me funcionó, todavia no encuentro el problema en mi código anterior, pero bueno, te comento que ya puedo descargar recibidos, saludos

**Comment by AllanCastro24** [comment]
Hola colegas, comencé de cero con la librería actualizada y ya funciona sin problemas, lo que detecté ahora es que el token expira, esto por qué el SAT mantiene una petición hasta 72 horas, lo que hice fue que entre mis peticiones agregué un método que renueva el token a los 2 minutos
