### ISSUE TITLE
Error al realizar obtener_token en autenticacion 

### ISSUE THREAD

**Issue by FernandaHerreraPbMx** [luisiturrios1/python-cfdiclient#45]
Antes realize el ejemplo completo y funcionaba perfectamente. Mas tarde volvi a probarlo y ya no funcionaba en la parte de auth.obtener_token() porque el valor de response.status_code es 500. A que se debe esto?
![image](https://user-images.githubusercontent.com/64936853/203660518-5b1a8d0b-814b-4c99-bee7-871374e28554.png)

**Comment by luisiturrios1** [comment]
Parece intermitencia por parte del SAT
