### ISSUE TITLE
Problema para descargar XML

### ISSUE THREAD

**Issue by AllanCastro24** [luisiturrios1/python-cfdiclient#47]
Hola! Tengo problemas para descargar los xml, los metadatos los descarga sin problema

**Comment by luisiturrios1** [comment]
Pudieras poner el error o explicar que problemas ?

**Comment by AllanCastro24** [comment]
Nunca descarga, se queda ciclado hasta que el token expira

con los metadatos no hay problema, el proceso lo hace de manera normal

**Comment by luisiturrios1** [comment]
Que te impide generar otro token? 

El sat se puede tomar hasta 72 horas en completar una solicitud
