### ISSUE TITLE
No descarga completo los XML y METADA recibida

### ISSUE THREAD

**Issue by AldoSoto3003** [luisiturrios1/python-cfdiclient#50]
Al ejecutar el programa primero tengo la descarga de cfdis emitidos y descarga bien, pero al llegar a los 
recibidos, solo descarga una cantidad muy pequeña, (por ejemplo, 16 y la cifra correcta son aprox 850).

Pero si ejecuto solo recibidos (comentando la ejecución de emitidos) ,  y luego vuelvo a ejecutar solo emitidos (comentando la ejecución de recibidos), si descarga la cantidad exacta tanto de recibidos, como de emitidos

**Comment by luisiturrios1** [comment]
Puede ser que exista un error con alguna variable de reducido en el ejemplo de descarga su fin solo es ser un ejemplo te recomendaría que lo separes y lo implementes con base a tus necesidades

**Comment by AldoSoto3003** [comment]
Hay una clase que se instancia llamada "SolicitaDescarga", se requiere reinstanciar, o limpiar el objeto antes de 
solicitar los emitidos, en mi caso, por el orden. Ya que al parecer el XML se lleva grabados los datos.

Lo dejo como comentario por si le pasa a alguien mas
