### ISSUE TITLE
Sistema se queda en loop

### ISSUE THREAD

**Issue by Roberto-RRF** [luisiturrios1/python-cfdiclient#51]
Que tal, 

Esta ultima semana el sistema ha estado muy lento, al grado de que este nunca regresa ningunn xml inclusive despues de horas de correr. A alguno de ustedes le funciona ?

Se queda trabado aqui: `SOLICITUD: {'cod_estatus': '5000', 'estado_solicitud': '2', 'codigo_estado_solicitud': '5000', 'numero_cfdis': '0', 'mensaje': 'Solicitud Aceptada', 'paquetes': []}`

Gracias!

**Comment by luisiturrios1** [comment]
Amigo debido a que este paquete se conecta a un servicio del SAT dependemos de que ese servicio este ok

**Comment by luisiturrios1** [comment]
Recientemente has logrado realizar solicitudes?

**Comment by luisiturrios1** [comment]
He estado realizando pruebas y funciona correctamente
