### ISSUE TITLE
Read time out

### ISSUE THREAD

**Issue by VMink** [luisiturrios1/python-cfdiclient#55]
Estuve utilizando la librería estos últimos meses sin ningún tipo de problema, hasta hace unos 3-4 días que siempre obtengo el siguiente código de error:

requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='cfdidescargamasivasolicitud.clouda.sat.gob.mx', port=443): Read timed out. (read timeout=15)

Realmente no se si sea problema de la librería o problema del servidor del SAT, pero no sabía donde más podía publicar mi problema y saber si a alguien más le había ocurrido.

**Comment by luisiturrios1** [comment]
Puedes intentar subir el timeout un poco más tiempo 

'''
verificacion = VerificaSolicitudDescarga(fiel, timeout=30)
'''

**Comment by Gera16** [comment]
No solo es el timeout, el SAT esta tardando mucho en procesar las solicitudes. Antes en cuestión de minutos/horas respondía, ahora pasan días y se queda en: 'mensaje': 'Solicitud Aceptada'.
Les pregunte en el chat pero no me dieron respuesta del porque se esta tardando de tanto.

**Comment by VMink** [comment]
Vale muchas gracias, esperemos entonces se solucione pronto del lado del SAT.
